//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaca
    {
        public int NRBrinco { get; set; }
        public System.DateTime DTNascimento { get; set; }
        public string TPSexo { get; set; }
        public Nullable<System.DateTime> DTInseminacao { get; set; }
        public Nullable<System.DateTime> DTDesamamentacao { get; set; }
        public Nullable<System.DateTime> DTProcriacao { get; set; }
    }
}
